name: Code Analysis

on:
    pull_request: null

jobs:
    code_analysis:
        strategy:
            fail-fast: false
            matrix:
                actions:
                    -
                        name: 'Validate'
                        run: composer validate --strict

                    -
                        name: 'Bare Run'
                        run: bin/console

                    -
                        name: 'ECS'
                        run: composer check-cs

                    -
                        name: 'PHPStan'
                        run: composer phpstan

        name: ${{ matrix.actions.name }}
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.1
                    coverage: none

            -   uses: "ramsey/composer-install@v1"

            -   run: ${{ matrix.actions.run }}
